app_actually/app_actually/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_actually/authapp/urls.py
from unicodedata import name
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

app_actually/basketapp/urls.py
from django.urls import path
from basketapp import views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove')
]

app_actually/basketapp/models.py
from django.db import models
from django.conf import settings

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)

    add_datetime = models.DateTimeField(auto_now_add=True)

    @property
    def product_cost(self):
        return self.quantity * self.product.price

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        return sum(list(map(lambda x: x.quantity, _items)))

    @property
    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        return sum(list(map(lambda x: x.product_cost, _items)))

app_actually/basketapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from basketapp.models import Basket
from mainapp.models import Product

@login_required
def basket(request):
    basket_list = Basket.objects.filter(user=request.user)

    context = {
        'baskets': basket_list
    }
    return render(request, 'basketapp/basket.html', context)

@login_required
def add(request, pk):
    product_item = get_object_or_404(Product, pk=pk)

    basket_item = Basket.objects.filter(product=product_item, user=request.user).first()

    if not basket_item:
        basket_item = Basket(product=product_item, user=request.user)

    basket_item.quantity += 1
    basket_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def remove(request, pk):
    basket_item = get_object_or_404(Basket, pk=pk)
    basket_item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

app_actually/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="basket_container">
    <div class="login">
        <div class="h2 text-center head">
            Ваша корзина, {% if user.first_name %}{{ user.first_name }}{% else %}Пользователь{% endif %}
        </div>

        {% block content %}
        {% endblock %}

    </div>
</div>
</body>
</html>

app_actually/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load static %}
{% block content %}
    <div class="basket_list">
        {% for item in baskets %}
            <div class="basket_record">
                <img src="/media/{{ item.product.image }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">{{ item.product.category.name }}</span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">{{ item.product.price }}&nbspруб</span>
                <input type="number"
                       name="{{ item.pk }}"
                       min="0"
                       value="{{ item.quantity }}">
                <span class="product_cost">{{ item.cost }}&nbspруб</span>
                <button class="btn btn-round">
                    <a href="{% url 'basket:remove' item.pk %}" class="">удалить</a>
                </button>
            </div>
        {% endfor %}
        {% if baskets %}
            <div class="basket_summary">
                В корзине {{ baskets.0.total_quantity }} товаров общей стоимостью {{ baskets.0.total_cost }} руб
            </div>
        {% endif %}
        <button class="btn btn-round">
            <a href="{% url 'index' %}">на главную</a>
        </button>
    </div>
{% endblock %}
Для разнообразия мы не стали использовать